//! C code generator: Whisper bytecode → standalone C program.
//! Produces a self-contained .c file with a full VM interpreter
//! supporting all 72 opcodes.  Compile with any C compiler.
//!
//! Usage:
//!   whisper build file.ws --target c -o file.c
//!   gcc -O2 file.c -o file -lm
//!   ./file                          # runs embedded bytecode
//!   ./file bytecode.wbin            # loads bytecode from file

use whisper_core::opcode::Opcode;
#[allow(unused_imports)]
use std::rc::Rc;

/// Generate a standalone C program from Whisper bytecode and word defs.
pub fn compile_to_c(bytecode: &[Opcode], defs: &[(String, Vec<Opcode>)]) -> String {
    let raw = raw_bytecode(bytecode);
    let bc_hex = hex_bytes(&raw);
    let bc_len = raw.len();
    let (word_table, word_dispatch) = gen_word_table(defs);

    format!(
        r##"// Generated by Whisper compiler — native C VM
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

// ── Opcodes ──────────────────────────────────────────────────────────
enum {{
    DUP=0x00, SWAP=0x01, DROP=0x02, ROT=0x03, PICK=0x04,
    ADD=0x10, SUB=0x11, MUL=0x12, DIV=0x13, MOD=0x14,
    EQ=0x18, LT=0x19, GT=0x1A, NEQ=0x1B, LE=0x1C, GE=0x1D,
    AND=0x20, OR=0x21, NOT=0x22,
    PUSH_I64=0x30, PUSH_F64=0x31, PUSH_STR=0x32, PUSH_BOOL=0x33, PUSH_LIST=0x34, PUSH_REF=0x35,
    NTH=0x40, APPEND=0x41, LEN=0x42, MAP=0x43, EACH=0x44, FOLD=0x45,
    STRLEN=0x46, STRCAT=0x47, STRSLICE=0x48, STREQ=0x49, STRLT=0x4A,
    STRFIND=0x4B, STRREPLACE=0x4C, STRTOI64=0x4D, I64TOSTR=0x4E, STRNTH=0x4F,
    COND=0x50, JUMP=0x51, LOOP=0x52, TIMES=0x53,
    CALL=0x60, RETURN=0x61,
    CAP_CALL=0x70, CAP_EXEC=0x71,
    CONF_LABEL=0x80, PROB_CHOICE=0x81,
    OUTPUT_TOP=0x90, OUTPUT_ALL=0x91, READ_INPUT=0x92,
    DEF_WORD=0xA0, END_DEF=0xA1, IMPORT=0xA2, EXPORT=0xA3,
    I64_TO_F64=0xB0, F64_TO_I64=0xB1, FSQRT=0xB2, FSIN=0xB3, FCOS=0xB4, FTAN=0xB5,
    JSON_PARSE=0xB6, JSON_STRINGIFY=0xB7,
    STRCHARS=0xB8, CHARSSTR=0xB9, STRITER=0xBA, LISTFIND=0xBB, STRJOIN=0xBC,
    BYTES_NEW=0xBD, BYTES_PUSH=0xBE, BYTES_LEN=0xBF, BYTES_WRITE=0xC0, TRY=0xC1,
}};

// ── Value types ──────────────────────────────────────────────────────
#define TAG_I64   0
#define TAG_F64   1
#define TAG_BOOL  2
#define TAG_STR   3
#define TAG_LIST  4

typedef struct {{ int tag; union {{ int64_t i; double f; int b; int s; }}; }} Value;
#define MAX_STACK 65536
#define MAX_STRS  4096
#define MAX_LISTS 16384
#define MAX_WORDS 256
#define MAX_FRAMES 1024
#define MAX_BC    262144

static Value     stack[MAX_STACK]; static int sp=0;
static char      strs[MAX_STRS][256]; static int nstr=0;
static Value     lists[MAX_LISTS][1024]; static int list_len[MAX_LISTS]; static int nlist=0;
static Value     tmp_list[1024];

static unsigned char embedded_bc[]={{
{bc_hex}
}};
static int embedded_bc_len = {bc_len};
static unsigned char bc[MAX_BC]; static int bc_len=0;
static int call_stack[MAX_FRAMES]; static int call_sp=0;
static int ip=0;
static uint64_t rng_state=123456789;

// ── Word table ───────────────────────────────────────────────────────
{word_table}

// ── Value helpers ────────────────────────────────────────────────────
static inline void push_i(int64_t v){{ Value x; x.tag=TAG_I64; x.i=v; stack[sp++]=x; }}
static inline void push_f(double v) {{ Value x; x.tag=TAG_F64; x.f=v; stack[sp++]=x; }}
static inline void push_b(int v)   {{ Value x; x.tag=TAG_BOOL; x.b=v; stack[sp++]=x; }}
static inline void push_s(int v)   {{ Value x; x.tag=TAG_STR; x.s=v; stack[sp++]=x; }}
static inline void push_l(int v)   {{ Value x; x.tag=TAG_LIST; x.s=v; stack[sp++]=x; }}

static inline int64_t  pop_i(void){{ return stack[--sp].i; }}
static inline double   pop_f(void){{ return stack[--sp].f; }}
static inline int      pop_b(void){{ return stack[--sp].b; }}
static inline int      pop_s(void){{ return stack[--sp].s; }}
static inline int      pop_l(void){{ return stack[--sp].s; }}

static inline int64_t  peek_i(void){{ return stack[sp-1].i; }}
static inline int      peek_tag(void){{ return stack[sp-1].tag; }}

static int str_push(const char *s){{
    int i=nstr++; strncpy(strs[i],s,255); strs[i][255]=0; return i;
}}
static int list_new(void){{
    int i=nlist++; list_len[i]=0; return i;
}}
static void list_push(int li, Value v){{
    if(list_len[li]<1024) lists[li][list_len[li]++]=v;
}}
static Value list_get(int li, int idx){{ return lists[li][idx]; }}

// ── Bytecode loader ──────────────────────────────────────────────────
static int read_i32(const unsigned char *p){{ return (int)(p[0]|(p[1]<<8)|(p[2]<<16)|(p[3]<<24)); }}
static int64_t read_i64(const unsigned char *p){{ return (int64_t)((uint64_t)p[0]|((uint64_t)p[1]<<8)|((uint64_t)p[2]<<16)|((uint64_t)p[3]<<24)|((uint64_t)p[4]<<32)|((uint64_t)p[5]<<40)|((uint64_t)p[6]<<48)|((uint64_t)p[7]<<56)); }}

static void load_bytecode(const unsigned char *data, int len){{
    memcpy(bc, data, len); bc_len=len;
}}
static int load_file(const char *path){{
    FILE *f=fopen(path,"rb"); if(!f) return 0;
    fseek(f,0,SEEK_END); long sz=ftell(f); fseek(f,0,SEEK_SET);
    if(sz>MAX_BC){{ fclose(f); return 0; }}
    bc_len=(int)fread(bc,1,sz,f); fclose(f);
    // Skip .wbin header (8 bytes magic)
    if(bc_len>8 && memcmp(bc,"WHISPER\x01",8)==0){{
        memmove(bc,bc+8,bc_len-8); bc_len-=8;
    }}
    return 1;
}}

// ── PRNG ─────────────────────────────────────────────────────────────
static double xorshift64(void){{
    rng_state^=rng_state>>12; rng_state^=rng_state<<25; rng_state^=rng_state>>27;
    return (double)(rng_state*0x2545F4914F6CDD1DULL>>11)/(double)(1ULL<<53);
}}

// ── Execution ────────────────────────────────────────────────────────
static int run_ref(const unsigned char *ref_bc, int ref_len, int base_sp){{
    call_stack[call_sp++]=ip; call_stack[call_sp++]=base_sp;
    int saved_ip=ip, saved_len=bc_len;
    memcpy(bc,ref_bc,ref_len); bc_len=ref_len; ip=0;
    // Execute until frame returns
    int ret=1, depth=call_sp;
    while(ip<bc_len){{
        unsigned char op=bc[ip++];
        switch(op){{
        case PUSH_I64: push_i(read_i64(&bc[ip])); ip+=8; break;
        case PUSH_F64: {{ int64_t bits=read_i64(&bc[ip]); ip+=8; double f; memcpy(&f,&bits,8); push_f(f); }} break;
        case PUSH_BOOL: push_b(bc[ip++]); break;
        case PUSH_STR: {{ int len=read_i32(&bc[ip]); ip+=4; char buf[256]={{0}}; memcpy(buf,&bc[ip],len<255?len:255); ip+=len; push_s(str_push(buf)); }} break;
        case PUSH_LIST: {{ int cnt=(int)pop_i(); int li=list_new(); for(int i=0;i<cnt;i++)list_push(li,stack[--sp]); push_l(li); }} break;
        case PUSH_REF: {{ int len=read_i32(&bc[ip]); ip+=4; run_ref(&bc[ip],len,sp); ip+=len; }} break;

        case DUP: {{ Value v=stack[sp-1]; stack[sp++]=v; }} break;
        case SWAP: {{ Value a=stack[--sp],b=stack[--sp]; stack[sp++]=a; stack[sp++]=b; }} break;
        case DROP: sp--; break;
        case ROT: {{ Value a=stack[--sp],b=stack[--sp],c=stack[--sp]; stack[sp++]=b; stack[sp++]=a; stack[sp++]=c; }} break;
        case PICK: {{ int n=bc[ip++]; stack[sp++]=stack[sp-1-n]; }} break;

        case ADD: {{ if(peek_tag()==TAG_F64||stack[sp-2].tag==TAG_F64){{ double b=pop_f(),a=pop_f(); push_f(a+b); }} else {{ int64_t b=pop_i(),a=pop_i(); push_i(a+b); }} }} break;
        case SUB: {{ if(peek_tag()==TAG_F64||stack[sp-2].tag==TAG_F64){{ double b=pop_f(),a=pop_f(); push_f(a-b); }} else {{ int64_t b=pop_i(),a=pop_i(); push_i(a-b); }} }} break;
        case MUL: {{ if(peek_tag()==TAG_F64||stack[sp-2].tag==TAG_F64){{ double b=pop_f(),a=pop_f(); push_f(a*b); }} else {{ int64_t b=pop_i(),a=pop_i(); push_i(a*b); }} }} break;
        case DIV: {{ if(peek_tag()==TAG_F64||stack[sp-2].tag==TAG_F64){{ double b=pop_f(),a=pop_f(); push_f(b!=0?a/b:0); }} else {{ int64_t b=pop_i(),a=pop_i(); push_i(b?a/b:0); }} }} break;
        case MOD: {{ int64_t b=pop_i(),a=pop_i(); push_i(b?a%b:0); }} break;

        case EQ: {{ if(stack[sp-1].tag==TAG_STR){{ int b=pop_s(),a=pop_s(); push_b(strcmp(strs[a],strs[b])==0); }} else if(stack[sp-1].tag==TAG_F64||stack[sp-2].tag==TAG_F64){{ double b=pop_f(),a=pop_f(); push_b(a==b); }} else {{ int64_t b=pop_i(),a=pop_i(); push_b(a==b); }} }} break;
        case LT: {{ double b=pop_f(),a=pop_f(); push_b(a<b); }} break;
        case GT: {{ double b=pop_f(),a=pop_f(); push_b(a>b); }} break;
        case NEQ: {{ if(stack[sp-1].tag==TAG_STR){{ int b=pop_s(),a=pop_s(); push_b(strcmp(strs[a],strs[b])!=0); }} else {{ int64_t b=pop_i(),a=pop_i(); push_b(a!=b); }} }} break;
        case LE: {{ double b=pop_f(),a=pop_f(); push_b(a<=b); }} break;
        case GE: {{ double b=pop_f(),a=pop_f(); push_b(a>=b); }} break;

        case AND: {{ int b=pop_b(),a=pop_b(); push_b(a&&b); }} break;
        case OR:  {{ int b=pop_b(),a=pop_b(); push_b(a||b); }} break;
        case NOT: {{ push_b(!pop_b()); }} break;

        case STRLEN: push_i((int64_t)strlen(strs[pop_s()])); break;
        case STRCAT: {{ int b=pop_s(),a=pop_s(); char buf[512]; snprintf(buf,sizeof(buf),"%s%s",strs[a],strs[b]); push_s(str_push(buf)); }} break;
        case STRSLICE: {{ int len=(int)pop_i(),start=(int)pop_i(),si=pop_s(); if(start<0)start=0; if(len<0)len=0; int slen=(int)strlen(strs[si]); if(start+len>slen)len=slen-start; if(start>slen)start=slen; char buf[256]; memcpy(buf,strs[si]+start,len); buf[len]=0; push_s(str_push(buf)); }} break;
        case STREQ: {{ int b=pop_s(),a=pop_s(); push_b(strcmp(strs[a],strs[b])==0); }} break;
        case STRLT: {{ int b=pop_s(),a=pop_s(); push_b(strcmp(strs[a],strs[b])<0); }} break;
        case STRFIND: {{ int pi=pop_s(),si=pop_s(); char *p=strstr(strs[si],strs[pi]); push_i(p?(int64_t)(p-strs[si]):-1); }} break;
        case STRREPLACE: {{ int ni=pop_s(),oi=pop_s(),si=pop_s(); char buf[512],*s=strs[si],*o=strs[oi],*n=strs[ni]; buf[0]=0; char *p=s; while(*p){{ char *f=strstr(p,o); if(f){{ strncat(buf,p,f-p); strcat(buf,n); p=f+strlen(o); }}else{{ strcat(buf,p); break; }}}} push_s(str_push(buf)); }} break;
        case STRTOI64: push_i((int64_t)atoll(strs[pop_s()])); break;
        case I64TOSTR: {{ char buf[32]; snprintf(buf,sizeof(buf),"%lld",(long long)pop_i()); push_s(str_push(buf)); }} break;
        case STRNTH: {{ int idx=(int)pop_i(),si=pop_s(); if(idx<0||(size_t)idx>=strlen(strs[si]))push_i(-1); else push_i((unsigned char)strs[si][idx]); }} break;

        case NTH: {{ int idx=(int)pop_i(),li=pop_l(); Value v=list_get(li,idx); stack[sp++]=v; }} break;
        case APPEND: {{ Value elem=stack[--sp]; int li=pop_l(); int ni=list_new(); for(int i=0;i<list_len[li];i++)list_push(ni,lists[li][i]); list_push(ni,elem); push_l(ni); }} break;
        case LEN: push_i((int64_t)list_len[pop_l()]); break;
        case MAP: {{ int ref_len=read_i32(&bc[ip]); ip+=4; const unsigned char *rb=&bc[ip]; ip+=ref_len; int li=pop_l(); int ni=list_new(); for(int i=0;i<list_len[li];i++){{ stack[sp++]=list_get(li,i); run_ref(rb,ref_len,sp-1); Value r=stack[--sp]; list_push(ni,r); }} push_l(ni); }} break;
        case EACH: {{ int ref_len=read_i32(&bc[ip]); ip+=4; const unsigned char *rb=&bc[ip]; ip+=ref_len; int li=pop_l(); for(int i=0;i<list_len[li];i++){{ stack[sp++]=list_get(li,i); run_ref(rb,ref_len,sp-1); }} }} break;
        case FOLD: {{ int ref_len=read_i32(&bc[ip]); ip+=4; const unsigned char *rb=&bc[ip]; ip+=ref_len; Value init=stack[--sp]; int li=pop_l(); stack[sp++]=init; for(int i=0;i<list_len[li];i++){{ stack[sp++]=list_get(li,i); run_ref(rb,ref_len,sp-2); }} }} break;

        case STRCHARS: {{ int si=pop_s(); int li=list_new(); const char *s=strs[si]; for(int i=0;s[i];i++){{ Value v;v.tag=TAG_I64;v.i=(unsigned char)s[i]; list_push(li,v); }} push_l(li); }} break;
        case CHARSSTR: {{ int li=pop_l(); char buf[1024]; int p=0; for(int i=0;i<list_len[li];i++){{ Value v=lists[li][i]; if(v.tag==TAG_I64 && v.i>0) buf[p++]=(char)v.i; }} buf[p]=0; push_s(str_push(buf)); }} break;
        case STRITER: {{ int si=pop_s(); if(strs[si][0]==0){{ push_i(-1); push_s(str_push("")); }} else {{ push_i((unsigned char)strs[si][0]); push_s(str_push(strs[si]+1)); }} }} break;
        case LISTFIND: {{ Value key=stack[--sp]; int li=pop_l(); int found=0; Value val; val.tag=TAG_I64;val.i=0; for(int i=0;i<list_len[li];i++){{ Value item=lists[li][i]; if(item.tag==TAG_LIST){{ int ili=item.s; if(list_len[ili]==2){{ Value k=lists[ili][0]; if(k.tag==key.tag){{ int eq=0; if(k.tag==TAG_I64)eq=(k.i==key.i); else if(k.tag==TAG_STR)eq=(strcmp(strs[k.s],strs[key.s])==0); if(eq){{ found=1; val=lists[ili][1]; break; }}}} }}}} push_b(found); stack[sp++]=val; }} break;
        case STRJOIN: {{ int li=pop_l(); char buf[4096]; buf[0]=0; for(int i=0;i<list_len[li];i++){{ Value v=lists[li][i]; if(v.tag==TAG_STR) strcat(buf,strs[v.s]); }} push_s(str_push(buf)); }} break;

        case COND: {{ int off=read_i32(&bc[ip]); ip+=4; if(!pop_b()) ip+=off; }} break;
        case JUMP: {{ int off=read_i32(&bc[ip]); ip+=4; ip+=off; }} break;
        case LOOP: {{ int off=read_i32(&bc[ip]); ip+=4; if(pop_b()) ip+=off; }} break;
        case TIMES: {{ int ref_len=read_i32(&bc[ip]); ip+=4; const unsigned char *rb=&bc[ip]; ip+=ref_len; int64_t n=pop_i(); for(int64_t i=0;i<n;i++)run_ref(rb,ref_len,sp); }} break;

        case CALL: {{ int name_len=bc[ip++]; char name[64]={{0}}; memcpy(name,&bc[ip],name_len); ip+=name_len; {wd} }} break;
        case RETURN: {{ call_sp-=2; if(call_sp>=0){{ sp=call_stack[call_sp]; ip=call_stack[call_sp-2]; memcpy(bc,bc_saved,sizeof(bc)); bc_len=bc_saved_len; }} else {{ ip=bc_len; }} }} break;

        case OUTPUT_TOP: {{ Value v=pop(); if(v.tag==TAG_STR)printf("%%s\n",strs[v.s]); else if(v.tag==TAG_F64)printf("%%.6f\n",v.f); else if(v.tag==TAG_BOOL){{ if(v.b)printf("#t\n"); else printf("#f\n"); }} else printf("%%lld\n",(long long)v.i); fflush(stdout); }} break;
        case OUTPUT_ALL: {{ printf("["); for(int i=0;i<sp;i++)printf("%lld ",(long long)stack[i].i); printf("]\n"); }} break;
        case READ_INPUT: {{ char buf[256]; if(fgets(buf,sizeof(buf),stdin)){{ buf[strcspn(buf,"\n")]=0; push_s(str_push(buf)); }} }} break;

        case I64_TO_F64: push_f((double)pop_i()); break;
        case F64_TO_I64: push_i((int64_t)pop_f()); break;
        case FSQRT: push_f(sqrt(pop_f())); break;
        case FSIN:  push_f(sin(pop_f())); break;
        case FCOS:  push_f(cos(pop_f())); break;
        case FTAN:  push_f(tan(pop_f())); break;

        case PROB_CHOICE: {{ int ref2_len=read_i32(&bc[ip]); ip+=4; const unsigned char *rb2=&bc[ip]; ip+=ref2_len; int ref1_len=read_i32(&bc[ip]); ip+=4; const unsigned char *rb1=&bc[ip]; ip+=ref1_len; if(xorshift64()<0.5)run_ref(rb1,ref1_len,sp); else run_ref(rb2,ref2_len,sp); }} break;

        case DEF_WORD: case END_DEF: case IMPORT: case EXPORT: break;
        default: break;
        }}
        if(call_sp<depth){{ ret=0; break; }}
    }}
    call_sp-=2; sp=call_stack[call_sp+1]; ip=call_stack[call_sp];
    memcpy(bc,bc_saved,bc_saved_len); bc_len=bc_saved_len;
    return ret;
}}

int run(void){{
    if(bc_len==0){{ memcpy(bc,embedded_bc,embedded_bc_len); bc_len=embedded_bc_len; }}
    return run_ref(bc,bc_len,0);
}}

int main(int argc, char **argv){{
    init_words();
    if(argc>1){{ if(!load_file(argv[1])){{ fprintf(stderr,"Cannot load %%s\n",argv[1]); return 1; }} }}
    return run();
}}
"##,
        word_table = word_table,
        bc_hex = bc_hex,
        bc_len = bc_len,
        wd = word_dispatch,
    )
}

/// Generate word dispatch table in C.
fn gen_word_table(defs: &[(String, Vec<Opcode>)]) -> (String, String) {
    let mut out = String::new();
    out.push_str("static unsigned char bc_saved[MAX_BC]; static int bc_saved_len=0;\n");
    out.push_str("static int word_bc_len[256]; static unsigned char word_bc[256][8192];\n");
    out.push_str("static const char *word_names[]={");
    for (i, (name, _)) in defs.iter().enumerate() {
        if i > 0 { out.push_str(", "); }
        out.push_str(&format!("\"{name}\""));
    }
    out.push_str(",NULL};\n");

    out.push_str("static void init_words(void){\n");
    for (i, (_, code)) in defs.iter().enumerate() {
        let raw = raw_bytecode(code);
        out.push_str(&format!(
            "  word_bc_len[{i}]={len}; memcpy(word_bc[{i}],\"{hex}\",{len});\n",
            i = i, len = raw.len(),
            hex = raw.iter().map(|b| format!("\\x{b:02X}")).collect::<String>()
        ));
    }
    out.push_str("}\n");

    let dispatch = "int w=-1; for(int i=0;word_names[i];i++){if(strncmp(name,word_names[i],name_len)==0&&(int)strlen(word_names[i])==name_len){w=i;break;}} if(w>=0){memcpy(bc_saved,bc,bc_len);bc_saved_len=bc_len;memcpy(bc,word_bc[w],word_bc_len[w]);bc_len=word_bc_len[w];call_stack[call_sp+1]=sp;call_stack[call_sp]=ip-1-name_len-1;call_sp+=2;ip=0;}".to_string();
    (out, dispatch)
}

/// Convert bytecode to raw bytes (.wbin format body).
fn raw_bytecode(ops: &[Opcode]) -> Vec<u8> {
    let mut buf = Vec::new();
    for op in ops {
        buf.push(op.to_byte());
        match op {
            Opcode::Pick(n) => buf.push(*n),
            Opcode::PushI64(n) => buf.extend_from_slice(&n.to_le_bytes()),
            Opcode::PushF64(n) => buf.extend_from_slice(&n.to_le_bytes()),
            Opcode::PushStr(s) => {
                buf.extend_from_slice(&(s.len() as u32).to_le_bytes());
                buf.extend_from_slice(s.as_bytes());
            }
            Opcode::PushBool(v) => buf.push(if *v { 1 } else { 0 }),
            Opcode::Cond(o) | Opcode::Jump(o) | Opcode::Loop(o) => {
                buf.extend_from_slice(&o.to_le_bytes())
            }
            Opcode::PushRef(inner) => {
                let inner_raw = raw_bytecode(inner);
                buf.extend_from_slice(&(inner_raw.len() as u32).to_le_bytes());
                buf.extend_from_slice(&inner_raw);
            }
            Opcode::Call(name) => {
                buf.push(name.len() as u8);
                buf.extend_from_slice(name.as_bytes());
            }
            Opcode::Map | Opcode::Each | Opcode::Fold | Opcode::Times => {
                // These are always followed by a PushRef — handled by the compiler
                // Here they have no extra data
            }
            _ => {}
        }
    }
    buf
}

fn hex_bytes(data: &[u8]) -> String {
    let mut lines = Vec::new();
    for chunk in data.chunks(16) {
        let line: Vec<String> = chunk.iter().map(|b| format!("0x{b:02X}")).collect();
        lines.push(format!("    {}", line.join(", ")));
    }
    lines.join(",\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_c_compile_hello() {
        let ops = vec![Opcode::PushStr(Rc::new("Hello".to_string())), Opcode::OutputTop];
        let c = compile_to_c(&ops, &[]);
        assert!(c.contains("int main"));
        assert!(c.contains("PUSH_STR"));
    }

    #[test]
    fn test_c_with_defs() {
        let defs = vec![("sq".to_string(), vec![Opcode::Dup, Opcode::Mul, Opcode::Return])];
        let ops = vec![Opcode::PushI64(5), Opcode::Call("sq".to_string()), Opcode::OutputTop];
        let c = compile_to_c(&ops, &defs);
        assert!(c.contains("\"sq\""));
        assert!(c.contains("init_words"));
    }

    #[test]
    fn test_c_full_vm() {
        let ops = vec![Opcode::PushI64(3), Opcode::PushI64(4), Opcode::Add];
        let c = compile_to_c(&ops, &[]);
        assert!(c.contains("ADD"));
        assert!(c.contains("MUL"));
        assert!(c.contains("MAP"));
        assert!(c.contains("CALL"));
        assert!(c.contains("LISTFIND"));
        assert!(c.contains("FSQRT"));
    }
}
