//! C code generator: Whisper bytecode → standalone C program.
//!
//! Produces a self-contained .c file that embeds the bytecode and
//! includes a minimal stack-based interpreter.  Compile with any
//! C compiler (gcc, clang, msvc) to get a native executable.
//!
//! Usage: whisper build file.ws --target c -o file.c
//!        gcc file.c -o file && ./file

use whisper_core::opcode::Opcode;

/// Generate a standalone C program from Whisper bytecode.
pub fn compile_to_c(bytecode: &[Opcode]) -> String {
    let raw = raw_bytecode(bytecode);
    let bc_hex = hex_bytes(&raw);
    let bc_len = raw.len();

    format!(
        r#"// Generated by Whisper compiler v1.0
// Standalone C program with embedded bytecode interpreter.

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ── Opcode definitions ─────────────────────────────────────────────
enum {{
    NOP = 0,    DUP = 0x00, SWAP = 0x01, DROP = 0x02, ROT = 0x03,
    ADD = 0x10, SUB = 0x11, MUL = 0x12, DIV = 0x13, MOD = 0x14,
    EQ  = 0x18, LT  = 0x19, GT  = 0x1A, NEQ = 0x1B, LE  = 0x1C, GE = 0x1D,
    AND = 0x20, OR  = 0x21, NOT = 0x22,
    PUSH_I64 = 0x30, PUSH_F64 = 0x31, PUSH_STR = 0x32,
    PUSH_BOOL = 0x33, PUSH_LIST = 0x34, PUSH_REF = 0x35,
    NTH = 0x40, APPEND = 0x41, LEN = 0x42,
    MAP = 0x43, EACH = 0x44, FOLD = 0x45,
    STRLEN = 0x46, STRCAT = 0x47, STRSLICE = 0x48,
    STREQ = 0x49, STRLT = 0x4A,
    COND = 0x50, JUMP = 0x51, LOOP = 0x52, TIMES = 0x53,
    CALL = 0x60, RETURN = 0x61,
    CAP_CALL = 0x70, CAP_EXEC = 0x71,
    CONF_LABEL = 0x80, PROB_CHOICE = 0x81,
    OUTPUT_TOP = 0x90, OUTPUT_ALL = 0x91, READ_INPUT = 0x92,
    I64_TO_F64 = 0xB0, F64_TO_I64 = 0xB1, FSQRT = 0xB2,
}};

// ── Bytecode ────────────────────────────────────────────────────────
static const unsigned char bytecode[] = {{
{bc_hex}
}};
static const int bc_len = {bc_len};

// ── Interpreter ─────────────────────────────────────────────────────
#define STACK_SIZE 4096
#define STRING_POOL 256
static int64_t  stack[STACK_SIZE];
static int      sp = 0;          // stack pointer (index of next free slot)
static char     string_pool[STRING_POOL][256];
static int      str_count = 0;

static inline void push(int64_t v)  {{ stack[sp++] = v; }}
static inline int64_t pop(void)     {{ return stack[--sp]; }}
static inline int64_t peek(void)    {{ return stack[sp-1]; }}

static int read_i32(const unsigned char *p) {{
    return (int)(p[0] | (p[1]<<8) | (p[2]<<16) | (p[3]<<24));
}}
static int64_t read_i64(const unsigned char *p) {{
    return (int64_t)((uint64_t)p[0] | ((uint64_t)p[1]<<8) |
           ((uint64_t)p[2]<<16) | ((uint64_t)p[3]<<24) |
           ((uint64_t)p[4]<<32) | ((uint64_t)p[5]<<40) |
           ((uint64_t)p[6]<<48) | ((uint64_t)p[7]<<56));
}}

static int str_push(const char *s) {{
    int idx = str_count++;
    strncpy(string_pool[idx], s, 255);
    return idx;
}}

int run(void) {{
    int ip = 0;
    while (ip < bc_len) {{
        unsigned char op = bytecode[ip++];
        switch (op) {{
        case PUSH_I64:  push(read_i64(&bytecode[ip])); ip += 8; break;
        case PUSH_F64:  push(read_i64(&bytecode[ip])); ip += 8; break;
        case PUSH_BOOL: push(bytecode[ip++]); break;
        case PUSH_STR: {{
            int len = read_i32(&bytecode[ip]); ip += 4;
            char buf[256] = {{0}};
            memcpy(buf, &bytecode[ip], len < 255 ? len : 255);
            buf[len < 255 ? len : 255] = 0;
            ip += len;
            push(str_push(buf));
        }} break;

        case DUP:  {{ int64_t v = peek(); push(v); }} break;
        case SWAP: {{ int64_t a = pop(), b = pop(); push(a); push(b); }} break;
        case DROP: pop(); break;

        case ADD:  {{ int64_t b = pop(), a = pop(); push(a + b); }} break;
        case SUB:  {{ int64_t b = pop(), a = pop(); push(a - b); }} break;
        case MUL:  {{ int64_t b = pop(), a = pop(); push(a * b); }} break;
        case DIV:  {{ int64_t b = pop(), a = pop(); push(b ? a / b : 0); }} break;
        case MOD:  {{ int64_t b = pop(), a = pop(); push(b ? a % b : 0); }} break;

        case EQ:   {{ int64_t b = pop(), a = pop(); push(a == b); }} break;
        case LT:   {{ int64_t b = pop(), a = pop(); push(a < b); }} break;
        case GT:   {{ int64_t b = pop(), a = pop(); push(a > b); }} break;
        case NEQ:  {{ int64_t b = pop(), a = pop(); push(a != b); }} break;
        case LE:   {{ int64_t b = pop(), a = pop(); push(a <= b); }} break;
        case GE:   {{ int64_t b = pop(), a = pop(); push(a >= b); }} break;

        case AND:  {{ int64_t b = pop(), a = pop(); push(a && b); }} break;
        case OR:   {{ int64_t b = pop(), a = pop(); push(a || b); }} break;
        case NOT:  {{ push(!pop()); }} break;

        case STRLEN: {{
            int idx = (int)pop();
            push((int64_t)strlen(string_pool[idx]));
        }} break;
        case STREQ: {{
            int b = (int)pop(), a = (int)pop();
            push(strcmp(string_pool[a], string_pool[b]) == 0);
        }} break;
        case STRLT: {{
            int b = (int)pop(), a = (int)pop();
            push(strcmp(string_pool[a], string_pool[b]) < 0);
        }} break;
        case STRCAT: {{
            int b = (int)pop(), a = (int)pop();
            char buf[256];
            snprintf(buf, sizeof(buf), "%s%s", string_pool[a], string_pool[b]);
            push(str_push(buf));
        }} break;

        case COND: {{
            int off = read_i32(&bytecode[ip]); ip += 4;
            if (!pop()) ip += off;
        }} break;
        case JUMP: {{
            int off = read_i32(&bytecode[ip]); ip += 4;
            ip += off;
        }} break;
        case LOOP: {{
            int off = read_i32(&bytecode[ip]); ip += 4;
            if (pop()) ip += off;
        }} break;

        case OUTPUT_TOP: {{
            int64_t v = pop();
            // Heuristic: if value looks like a string index, print string
            if (v >= 0 && v < str_count) {{
                printf("%s\n", string_pool[(int)v]);
            }} else {{
                printf("%lld\n", (long long)v);
            }}
        }} break;
        case OUTPUT_ALL: {{
            printf("Stack: [");
            for (int i = 0; i < sp; i++) printf("%lld ", (long long)stack[i]);
            printf("]\n");
        }} break;
        case READ_INPUT: {{
            char buf[256];
            if (fgets(buf, sizeof(buf), stdin)) {{
                buf[strcspn(buf, "\n")] = 0;
                push(str_push(buf));
            }}
        }} break;

        case RETURN: ip = bc_len; break;
        default: break;
        }}
    }}
    return 0;
}}

int main(void) {{
    return run();
}}
"#
    )
}

/// Convert bytecode to raw bytes (same format as .wbin body).
fn raw_bytecode(ops: &[Opcode]) -> Vec<u8> {
    let mut buf = Vec::new();
    for op in ops {
        buf.push(op.to_byte());
        match op {
            Opcode::Pick(n) => buf.push(*n),
            Opcode::PushI64(n) => buf.extend_from_slice(&n.to_le_bytes()),
            Opcode::PushF64(n) => buf.extend_from_slice(&n.to_le_bytes()),
            Opcode::PushStr(s) => {
                buf.extend_from_slice(&(s.len() as u32).to_le_bytes());
                buf.extend_from_slice(s.as_bytes());
            }
            Opcode::PushBool(v) => buf.push(if *v { 1 } else { 0 }),
            Opcode::Cond(o) | Opcode::Jump(o) | Opcode::Loop(o) => {
                buf.extend_from_slice(&o.to_le_bytes())
            }
            Opcode::PushRef(inner) => {
                buf.extend_from_slice(&(inner.len() as u32).to_le_bytes());
                let inner_raw = raw_bytecode(inner);
                buf.extend_from_slice(&inner_raw);
            }
            _ => {}
        }
    }
    buf
}

/// Format bytes as C hex array initializer.
fn hex_bytes(data: &[u8]) -> String {
    let mut lines = Vec::new();
    for chunk in data.chunks(16) {
        let line: Vec<String> = chunk.iter().map(|b| format!("0x{b:02X}")).collect();
        lines.push(format!("    {}", line.join(", ")));
    }
    lines.join(",\n")
}

// ── Tests ────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_c_compile_hello() {
        let ops = vec![Opcode::PushStr(std::rc::Rc::from("Hello, World!")), Opcode::OutputTop];
        let c_code = compile_to_c(&ops);
        // String literals are in bytecode hex, not directly in C source
        assert!(c_code.contains("int main(void)"));
        assert!(c_code.contains("bytecode[]"));
        assert!(c_code.contains("0x32")); // PUSH_STR opcode byte
    }

    #[test]
    fn test_c_compile_arithmetic() {
        let ops = vec![
            Opcode::PushI64(3),
            Opcode::PushI64(4),
            Opcode::Add,
            Opcode::OutputTop,
        ];
        let c_code = compile_to_c(&ops);
        assert!(c_code.contains("PUSH_I64"));
        assert!(c_code.contains("0x30"));
        // 3 and 4 should be in bytecode as i64 LE
        assert!(c_code.len() > 500);
    }

    #[test]
    fn test_c_empty() {
        let c_code = compile_to_c(&[]);
        assert!(c_code.contains("int main"));
    }
}
